name: "Test"

services:
  flask:
    build:
      context: .
      dockerfile: flask-service/dockerfile
    ports:
      - "5001:${FLASK_PORT}"
    volumes:
      - "./flask-service:/app/flask"
    restart: always
    env_file:
      - .env

  fastapi:
    build:
      context: .
      dockerfile: fastapi-service/dockerfile
    ports:
      - "8001:${FASTAPI_PORT}"
    volumes:
      - "./fastapi-service:/app/fastapi"
    restart: always
    env_file:
      - .env

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
    restart: always
    env_file:
      - .env

networks:
  default:
    driver: bridge
